# Generated by Django 4.1.7 on 2023-06-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehboobProject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=64)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=264)),
                ('phoneNumber', models.IntegerField()),
                ('previous_school', models.CharField(max_length=64)),
                ('previous_class', models.IntegerField()),
                ('percentage', models.FloatField()),
            ],
        ),
    ]
