# Generated by Django 4.1.7 on 2023-06-24 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehboobProject', '0002_studentsadmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsadmission',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(21), django.core.validators.MinValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='studentsadmission',
            name='percentage',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='studentsadmission',
            name='phoneNumber',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='studentsadmission',
            name='previous_class',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
