# Generated by Django 4.1.7 on 2023-06-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mehboobProject', '0003_alter_studentsadmission_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsadmission',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='studentsadmission',
            old_name='phoneNumber',
            new_name='phone',
        ),
    ]
