# Generated by Django 4.1.7 on 2023-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mehboobProject', '0005_alter_studentsadmission_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField(max_length=264)),
            ],
        ),
    ]
